GET http://localhost:3000/api/v1/products

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name": "Incredible Plastic Pants",
  "price": 827.00,
  "brand": "Hauck - Johnson",
  "image": "http://loremflickr.com/640/480/fashion"
}

###
GET http://localhost:3000/api/v1/products/4

###
PATCH  http://localhost:3000/api/v1/products/4
Content-Type: application/json

{
  "name": "TESTANDO"
}

###
DELETE http://localhost:3000/api/v1/products/6